<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(MavueWindowsTfm)</TargetFramework>
    <TargetPlatformMinVersion>$(MavueMinWindows)</TargetPlatformMinVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Mavue.Image\Mavue.Image.csproj" />
  </ItemGroup>
</Project>
